### ISSUE TITLE
suggestion to improve the DDA  in PeptideShaker

### ISSUE THREAD

**Issue by FazeH** [compomics/peptide-shaker#125]
Hi PeptideShaker developers,
I have been reading the new paper from Zubarev's group (http://www.ncbi.nlm.nih.gov/pubmed/26729709). The paper shows the power of DeMix-Q algorithm to alleviate the missing values problem in DDA. 
I believe the proteomics community can benefit greatly from this algorithm to address one of the intrinsic issues of  DDA (http://pubs.acs.org/doi/abs/10.1021/pr501138h). 
Is there anyway to have this implemented in PeptideShaker? 
Thanks
HFaz

**Comment by mvaudel** [comment]
Dear HFaz,

Thank you for bringing this interesting paper to our attention. At the moment we do not have a solution for the comparison of different samples. We will certainly consider this when implementing it :)

Best regards,

Marc

**Comment by hbarsnes** [comment]
Hi HFaz,

As this is not really an issue, but more of a suggestion for future already planned features, we will close the issue in order to make it easier for us to maintain the overview of the current "real" issues. Your suggestion has been noted though, and we'll definitely consider it when implementing the PeptideShaker project comparison.

Best regards,
Harald
