### ISSUE TITLE
Proteowizard requirement

### ISSUE THREAD

**Issue by FazeH** [compomics/peptide-shaker#131]
Hi,
I have been trying to use PeptideShaker on my Mac (OS X Yosemite, 10.10.5) for a .mzXML file. I get the  message that "Proteowizard is required to convert Raw files". 
<img width="859" alt="screen shot 2016-02-03 at 12 50 48 pm" src="https://cloud.githubusercontent.com/assets/13034441/12791437/2e4eaea8-ca75-11e5-9980-00daf27e1d04.png">
The .mzXML file was generated by using Proteowizard to convert a .raw file on a separet PC. 
Any thoughts? 
Thanks and I look forward to hearing from you.
HFaz

**Comment by hbarsnes** [comment]
Hi HFaz,

We use ProteoWizard to read/convert all spectrum files except for mgf. So if you want to use other formats than mgf as input in SearchGUI you will have to install ProteoWizard.

However, while converting vendor format raw files is only supported on Windows, I think you should be able to convert mzML and mzXML files in the OS X version of ProteoWizard as well. The other option is to convert the raw file to mgf instead of mzXML before processing the data on your Mac.

Best regards,
Harald
