### ISSUE TITLE
How to filter out the reliable identification under 1% FDR

### ISSUE THREAD

**Issue by Fiona-dym** [compomics/peptide-shaker#147]
I set FDR at all levels as 1%, then export the results (The database search engine was Mascot). I wonder if all PSMs in the the result file are reliable or how to filter out the reliable match under 1% FDR, because there is no value can help to make a judgement except the confidence. I have checked the ion score distribution by parsing the Mascot dat in view of these confident PSM given by peptide-shaker. Many PSMs have very low scores below 10. So how to get the reliable identification under 1% FDR?

The command used:
java -Djava.awt.headless=true -cp ./SearchGUI-2.6.5/SearchGUI-2.6.5.jar eu.isas.searchgui.cmd.IdentificationParametersCLI -out search_new.par -variable_mods "iTRAQ 4-plex of Y,Oxidation of M" -fixed_mods "Carbamidomethylation of C,iTRAQ 4-plex of K,iTRAQ 4-plex of peptide N-term" -db swissprot_mouse_target_decoy.fasta -prec_tol 10 -frag_tol 0.05 -max_charge 5 -max_isotope 1 -useGeneMapping 0 -updateGeneMapping 0 -annotation_level 0.02 -import_peptide_length_min 7 -import_peptide_length_max 45 -ptm_score 2 -score_neutral_losses 0 -db_pi  swissprot_mouse_target_decoy.fasta -psm_fdr 1 -peptide_fdr 1 -protein_fdr 1

java -Xmx8G -cp ./PeptideShaker-1.7.6/PeptideShaker-1.7.6.jar eu.isas.peptideshaker.cmd.PeptideShakerCLI -experiment 2016 -sample Mouse -replicate 1 -identification_files ./asc-nodecoy/1.asc.dat -out ./1-MASCOT.cpsx -spectrum_files 1.mgf -id_params search_new.par -temp_folder tmp/

java -Xmx8G -cp  ./PeptideShaker-1.7.6/PeptideShaker-1.7.6.jar eu.isas.peptideshaker.cmd.ReportCLI -in 1-MASCOT.cpsx -out_reports output -temp_folder export_tmp/ -reports 3,5,7,8

**Comment by mvaudel** [comment]
Hi and thank you for contacting us,

When importing Mascot results the e-value provided is used and not the ion score. It can be that some of these matches present a good e-value but a poor ion score. A low Mascot ion score does not necessarily mean a bad match, and conversely there are false positives with very high scores :) I am not sure what you mean with reliable identification though?

The threshold is set so that you have 1% of false positives estimated from the distribution of decoy hits. If you want to be more stringent, you can go below 1% - e.g. 0.1% - this will include hits with higher e-value only. Additionally, the tool conducts some additional quality control based on the ion coverage, mass deviation, etc. The matches not passing this quality control are marked as Doubtful. It is not necessary to filter them out but you might want to be critical with these.

Did you open the cpsx file in the PeptideShaker graphical interface? It might be a good way to see which matches to trust independently from the Mascot score.

Hope this helps, don't hesitate to write again if anything is unclear,

Marc

**Comment by hbarsnes** [comment]
(Issue assumed fixed. If this is not the case, please let us know and we'll reopen the issue.)
