### ISSUE TITLE
Unable to import data

### ISSUE THREAD

**Issue by dpapasotiriou** [compomics/peptide-shaker#152]
Hi,

I have been trying to import data into peptide shaker. I am using Andromeda + X! TAndem + Comet as search engines. I receive the following message: 

Mon Apr 11 02:17:32 BST 2016        An error occurred: The statement was aborted because it would have caused a duplicate key value in a unique or primary key constraint or unique index identified by 'SQL160408130723340' defined on 'PROTEINS'.

I have included a copy of the report as an attachment.

Thank you,
Dimitri

[Failed import.txt](https://github.com/compomics/peptide-shaker/files/212595/Failed.import.txt)

**Comment by mvaudel** [comment]
Hi Dimitri and thank you for reporting this issue.

Can it be that you have multiple projects open simultaneously, or another instance of PeptideShaker not properly closed? You will see other instances in the task manager.

If so please try to close all other instances running - to be sure you can also restart your computer - and then try to export it again.

Can you also make sure that PeptideShaker and the files are located locally on the computer and not on a network? Also, that the tool and files are not on a folder mapped to a network drive? This error can happen when the tool looses its access to the back-end database. Since the error occurred just after midnight, could it be that the connection was reset or lost somehow?

Apologies for the inconvenience,

Marc

**Comment by dpapasotiriou** [comment]
Hi Marc,

I am conducting the search on a local PC in the lab and accessing it remotely. All files and databases are located on the same local drive, but in different folders. Could that be the problem? 

Also, I can confirm that there is no other instance of PeptideShaker running in the background.

I'll restart the computer and try importing the data once again and let you know.

Great application by the way. I've been enjoying PeptideShaker for a few weeks now. MS1 quantification would be a very useful addition for future releases.

Thanks,
Dimitri

**Comment by mvaudel** [comment]
Hi Dimitri,

Thank you for the kind words. Hopefully the tool will handle the data this time. It seems that all was going fine on sunday at 11 pm and monday at 2 am the connection was lost.

MS1 quantification is high up on our todo list but will require few months/years of work before we can release it publicly.

Best regards,

Marc

**Comment by hbarsnes** [comment]
Hi Dimitri,

This issue is assumed resolved in the latest release of PeptideShaker. If this is not the case, please let us know and we'll reopen the issue.

Best regards,
Harald
