### ISSUE TITLE
High ppm errors

### ISSUE THREAD

**Issue by hale94** [compomics/peptide-shaker#153]
Sometimes when a search is completed, the ppm errors are very high (ie 30000).  This does not happen every time a search is done.  I repeated a search on a single data set 3 times.  Two times the results were good (ppms generally less than 10).  On the third, some of the peptides were showing high ppm errors,  even though I have the ppm cutoff set at 10 ppm in searchgui.

This has been occurring for a month or so.

**Comment by hbarsnes** [comment]
Thanks for telling us about this. We are aware of the issue and have been trying to come up with a fix for some time: https://github.com/compomics/peptide-shaker/issues/126. The issue seems to be related to the use of multiple threads/cores, i.,e. running multiple parallel processes, which for some reason can end up confusing our peptide (or amino acid) mass calculation. We have made one fix already, which seemed to fix the problem. But it is now clear that this was not enough. We have therefore started working on this issue again and will hopefully come up with a proper fix soon.

Best regards,
Harald

**Comment by hbarsnes** [comment]
Hi again,

BTW, which search engines were you using? And if the dataset is not too big would it be possible for you to share the SearchGUI output with us?

Best regards,
Harald

**Comment by hbarsnes** [comment]
Hi again,

We've found and fixed a bug that hopefully corrects the problem with the high ppm errors. A beta version is available for testing here: https://www.dropbox.com/s/4g4dcfy43yt9o1x/PeptideShaker-1.10.0-beta.zip?dl=0

It would be great if you could test this version and see if it solves the problem for your data.

Best regards,
Harald

**Comment by hale94** [comment]
Harald,

 

I ran a dataset that had failed twice previously, and it worked with the beta version.  Thanks for addressing this.

 

John

**Comment by ulrich-eckhard** [comment]
same here!!! looks great!!!

**Comment by hbarsnes** [comment]
Hi John, hi Ulrich,

Great! We'll release a proper new version as soon as possible. Hopefully next week.

Best regards,
Harald

**Comment by hbarsnes** [comment]
Hi John, hi Ulrich,

PeptideShaker v1.10.0 has now been released which should fix this issue.

Best regards,
Harald

**Comment by hale94** [comment]
Thanks Harald.
