### ISSUE TITLE
question about unassigned spectra 

### ISSUE THREAD

**Issue by FazeH** [compomics/peptide-shaker#154]
Hi All,
In one of my projects, I am trying to extract the unassigned spectra and search them against a different database. The new database contains sample-specific novel variations that are absent in my first database. What is the best practice? should I do my second search only on "Spectra of Non-Validated PSMs" from the first search? 
Thanks
HFaz

**Comment by mvaudel** [comment]
Hi HFaz,

Yes, exporting the spectra of non-validated PSMs is the best way to construct these follow-up searches. However, the relevance of such approaches is subject to debate in the community due to the difficulty to control the error rates of the second search, and I am afraid there is no consensus on a best practice.

One of the main problems in my eyes is that it is not because a PSM is not validated that it is incorrect, many of those hits are false negatives. And when searching the corresponding spectra against a different database, you might end up forcing the algorithm to find what you want to find. If your novel variants do not represent too many peptides, I would just add them to the original fasta file and keep a fair competition between sequences. If it is a problem, I would recommend using this second search to identify the most promising candidates and then rerun the original search with original sequences + variants. This combination of approaches might put you on the safe side in terms of false positive identifications. You might also want to try thresholding the first search at 1% FNR instead of 1% FDR in order to limit the number of false negatives considered in the second search. 

These are only personal considerations and I have no data to prove that one approach is better than the other. I can thus not give any guarantee, and can only recommend being skeptical with the results and cautious with regards to false positives. You will find very good input on this topic here:
http://www.matrixscience.com/blog/search-only-for-peptides-we-care-about.html#comments

Hope this helps,

Marc
