### ISSUE TITLE
Error when I used multiple search engines

### ISSUE THREAD

**Issue by fazeliniah** [compomics/peptide-shaker#176]
Hi,
I am using three search engines (comet, MS-GF+ ,and X!tandem) for my searches using an RNA-based custom database. The peptide shaker fails at the very last step (Validating identifications at 1% FDR, quality control of matches.). I have attached the reports for your review. 
My searches were successful when I used only one search engine (MS-GF+). 
I appreciate your help in advance. 
Thanks
fazeliniah
[PeptideShaker 1.10.3 log.txt](https://github.com/compomics/peptide-shaker/files/294700/PeptideShaker.1.10.3.log.txt)
[20160601_PS_report_failed.txt](https://github.com/compomics/peptide-shaker/files/294701/20160601_PS_report_failed.txt)

**Comment by hbarsnes** [comment]
Hi Fazeliniah,

Thanks for telling us about this. It seems like you have a problem with your FASTA file. Note the following warning:

> Some peptides could not be mapped to the database. Please verify the following:
- The protein sequence database must be the same or contain the database used for the search.
- When using the 'REVERSED' tag, decoy sequences must be reversed versions of the target sequences, use the 'DECOY' tag otherwise.
- When using in house databases make sure that the format is recognized by search engines and PeptideShaker (more details at http://compomics.github.io/searchgui/wiki/databasehelp.html)

Did you check the above tips? Especially make sure that you are using the exact same FASTA file for both the search in SearchGUI and the processing in PeptideShaker.

Also, please make sure that you are only running one instance of PeptideShaker at the same time, as the "aborted because it would have caused a duplicate key" message could indicate that you are using accessing the underlying database more than once at the same time.

Best regards,
Harald

**Comment by hbarsnes** [comment]
Hi Fazeliniah,

As we didn't hear back from you we assume that the issue has now been resolved? If this is not the case, please let us know and we'll reopen the issue.

Best regards,
Harald
