### ISSUE TITLE
Error while loading .dat files

### ISSUE THREAD

**Issue by yishai99** [compomics/peptide-shaker#194]
Hi, I tried loading *.dat files into PeptideShaker but got an error.
The .dat file can be downloaded from here: https://owncloud.incpm.weizmann.ac.il/index.php/s/fI1uqsG5LsQ3V6G
Database: https://owncloud.incpm.weizmann.ac.il/index.php/s/sDwOT9UoV93Cyum
Also attached are the logs.

Thanks,

Yishai
[PeptideShaker 1.12.1 log.txt](https://github.com/compomics/peptide-shaker/files/381269/PeptideShaker.1.12.1.log.txt)
[Error_WIS_250716.txt](https://github.com/compomics/peptide-shaker/files/381268/Error_WIS_250716.txt)

**Comment by hbarsnes** [comment]
Hi Yishai,

Thanks for telling us about this. The problem seems to be your mgf file: "Cannot parse retention time: 0.29016185+".

I'm not sure how such a retention time ought to be processed? And is does not seem to be valid according to the mgf format: http://www.matrixscience.com/help/data_file_help.html#SCANS?

How did you generate the mgf file?

Best regards,
Harald

**Comment by hbarsnes** [comment]
Hi Yishai,

As we didn't hear back from you I assume that you managed to solve the problem? If this is not the case please let us know and we'll reopen the issue.

Best regards,
Harald
