### ISSUE TITLE
Errors building the PeptideShaker Maven project

### ISSUE THREAD

**Issue by KenWifi** [compomics/peptide-shaker#203]
Hi,

I  tried to compile PeptideShaker by myself in recent days, but from last week it had some problems to compile. The problem is that I cannot download some repositories online. Such as http://genesis.UGent.be/maven2/batik/batik-all/1.6/batik-all-1.6.pom and many ones on  'http://www.ebi.ac.uk/'. But it could work friendly one week ago. Do you have any idea to help me?
I will appreciate it if you have any advice.

Ken

**Comment by hbarsnes** [comment]
Hi Ken,

I'm afraid there is nothing we can do at the moment. We have the same issues on our side. It's all due to the EBI going offline for planned maintenance August 26th to 30th, and some services are not yet back online due to unknown issues. Hopefully they will come back online soon. I will keep you posted.

Best regards,
Harald

**Comment by KenWifi** [comment]
Thank you very much!

**Comment by hbarsnes** [comment]
Hi Ken,

The EBI repositories are now back online and you should be able to build our projects again.

Best regards,
Harald
