### ISSUE TITLE
How is the "Confidence" calculated

### ISSUE THREAD

**Issue by dblyon** [compomics/peptide-shaker#213]
Dear Compomics-team,

I would very much like to **understand how the "confidence" metric in peptideShaker is calculated**. PeptideShaker's graphs and metrics make a lot of sense and the explanations are great (FDR, FNR, PEP, etc.). It makes sense to use a confidence level, but in order to apply it properly to specific data/search parameters, I need to understand how it is computed. I can't find any description of how exactly you calculate the confidence, to arrive at a confidence level of e.g. 90%. 

I've looked at 
- Vaudel et al., Peptide identification quality control, Proteomics 2011
- Vaudel et al, PeptideShaker enables reanalysis of MS-derived proteomics data sets, Nature Methods 2015
as well as 
- the tutorial (http://genesis.ugent.be/files/costore/practicals/bioinformatics-for-proteomics/1-Peptide-and-Protein-Identification/1.5-Peptide-and-Protein-Validation/1.5-Peptide-and-Protein-Validation.pdf)

Please point me to the proper material (publication, supplement, website, tutorial, etc.) or explain it here if possible. 

Thank you for your time and efforts!

Best regards,
David

**Comment by mvaudel** [comment]
Hi David,

In PeptideShaker the "confidence" is just _1-PEP_. So if you got FDR, FNR, and PEP the most difficult is done! When you set a 95% confidence threshold, the tool goes from the best scoring hits to the worse, and stops just before the first one going under 95%.

In many cases it makes a lot of sense to use the confidence for setting the line between what you want to keep or not, but as you can see in the plots, the scores are not always very good at separating the good from the bad. As a result, the confidence might fluctuate instead of simply decreasing when the score decreases. When using global metrics like the FDR, the error rates are averaged and hence smoothed. They are therefore generally preferred because more robust :)

Hope this helps, don't hesitate to write again if you need more help on this! If you want more documentation on this I always advise to read the [review by Alexey Nesvizhskii on this](https://www.ncbi.nlm.nih.gov/pubmed/?term=20816881) - although I appreciate that you went through my modest contributions ;) Also a bit of advertisement: if you want to sharpen your bioinformatics skills I recommend joining the [Eubic Winter School](https://www.fh-ooe.at/en/kongresse/2017/eubic/) where these topics will be discussed in details!

Marc

**Comment by dblyon** [comment]
Thank you for the explanation!! :)

(I've got some more questions concerning filtering in peptideShaker, but will post them separately to make it searchable.)

**Comment by antortjim** [comment]
Hi David and Marc

I have the same question too, and Marc's answer didn't fully answer it, for me at least :P So how is the PEP computed in peptideShaker?  According to https://www.ncbi.nlm.nih.gov/pubmed/18052118, the PEP or local FDR of a PSM is just the minimal global FDR at which that PSM is included in the list of positives. According to [Nesvizhskii](https://www.ncbi.nlm.nih.gov/pubmed/?term=20816881):

> the posterior probability of an individual PSM (1 – fdr) [fdr being the PEP] is an estimated fraction of correct PSMs among a collection of PSMs having similar search scores (or similar p-values/E-values)

So the reason why the confidence fluctuates, as opposed to monotonically increase with higher scores would be traced back to, under my understanding, the fluctuation of the estimated fraction of wrong PSMs at each score. So for instance, at a higher score, there will not always be a lesser fraction of wrong PSMs (even though on average there will indeed), just because of random fluctuations.

But how is the PEP computed in peptideShaker? Does it work like PeptideProphet, which attempts to fit 2 distributions to the latent distributions of wrong and right matches, from which the ratio can be used as an estimate of the PEP?

Below I am showing Figure 1 from https://www.ncbi.nlm.nih.gov/pubmed/18052118 which I have found really useful to clarify the concepts, for anyone having similar questions.

Thank you so much beforehand!

Best
Antonio

![pep](https://user-images.githubusercontent.com/13869571/42410642-33e32880-81ed-11e8-959a-a3a252c46506.png) Taken from  https://www.ncbi.nlm.nih.gov/pubmed/18052118

**Comment by mvaudel** [comment]
Hi Antonio,

In PeptideShaker the PEP at a given score X is estimated by setting a window of N target hits around X and computing b/(a + b) like in your illustration where b is estimated by the number of decoy hits in the window and a + b is estimated by the number of target hits. N is the maximal number of target hits between two consecutive decoy hits.

Hope this helps and sorry for the delay answering!

Marc
