### ISSUE TITLE
Peptide Shaker GUI bug report

### ISSUE THREAD

**Issue by carlaurangasolis** [compomics/peptide-shaker#215]
[PeptideShaker BugReport 1.13.6 log.txt](https://github.com/compomics/peptide-shaker/files/546157/PeptideShaker.BugReport.1.13.6.log.txt)

Hi, is this a memory issue as well? I was able to generate all reports etc. via the Peptide Shaker CLI however the Peptide Shaker GUI refused to open the results because of various syntax errors described in the bug report. I was able to run a partial NCBI dataset, but still, it is more than a million sequences and I am unable to see the overview and various other Peptide Shaker GUI functions. Thank you very much!

**Comment by hbarsnes** [comment]
From what I can see from the log file there seems to be something wrong with your PeptideShaker project. Perhaps something went wrong during the saving, as all the error messages at the end are related to incorrect queries to the backend database of PeptideShaker. Like this one: "Syntax error: Encountered "oxidase" at line 1, column 114."

Another reason might be strange accession numbers for the proteins in your FASTA file that are not parsed correctly. It this database small enough so that you can share it? Or can you tell us specifically how you created it so that we can recreate the same database?

**Comment by carlaurangasolis** [comment]
Hello, so for now the NCBI database is 1GB, therefore I am trying to use dropbox. However that issue aside, it is probably better to stick to Uniprot, which already worked well. However, the Uniprot database has only worked using MSGF and Comet. When I try using the Uniprot database with OMSSA and Myrimatch I get the following error:

Info: Using 24 search threads
"omssacl.cpp", line 216: Fatal: COMSSA::Run() - Unable to open blast library uniprot_all_concatenated_target_decoy.fasta with error:NCBI C++ Exception:
    "/net/frosty/vol/export1/proteomics_alg/projects/omssa/c++/src/objtools/blast/seqdb_reader/seqdbalias.cpp", line 319: Error: ncbi::CSeqDBAliasNode::x_ResolveNames() - No alias or index file found for protein database [uniprot_all_concatenated_target_decoy.fasta] in search path [/LUSTRE/curanga/proteomica/SearchGUI-3.1.1::]

I downloaded the database from Uniprot, and it only contains reviewed sequences. Thank you for your help!

Sincerely,

Carla Uranga, M.Sc.

**Comment by hbarsnes** [comment]
Hi Carla,

It seems like OMSSA is having trouble parsing your FASTA file. It could simply be that the FASTA file is too big for OMSSA to handle. As this looks similar to what we've seen when the spectrum files get too big for OMSSA. If this is indeed the case (as you can try by searching against a smaller version of your database), I would recommend that you replace OMSSA by one of the other search engines.

You mention that you also have an error for MyriMatch? I don't see that error above though?

Regarding the FASTA file you shared with me via Dropbox, would it be possible for you to instead of sharing the folder rather send me the link to download the file? (As I don't have enough room on my Dropbox to share the folder.)

Best regards,
Harald

**Comment by hbarsnes** [comment]
Hi Carla,

I would recommend updating to the new releases of SearchGUI and PeptideShaker to see if this solves the problems. If not, please open a new issue for the new bug report and we'll see what we can do.

Best regards,
Harald
