### ISSUE TITLE
Peptide shaker import warnings (help wanted)

### ISSUE THREAD

**Issue by wolski** [compomics/peptide-shaker#250]
I am importing search results and getting the following warnings.

Fri Mar 03 12:13:12 CET 2017        Warning: More than 75% of the PSMs did not pass the import filters.
 Please verify that your peptide selection criteria are not too restrictive.
 Please verify that your precursor selection criteria are not too restrictive.
 Apparently, your data contains modifications which are not recognized by PeptideShaker. Please verify the search parameters provided when creating the project.

So my questions are: If the selection criteria are too restrictive, where can I modify them?
I am importing search results generated with SearchGUI. Which makes me wonder why some modifications are not recognized by PeptideShaker? 

Thank you

**Comment by mvaudel** [comment]
Hi,

The import filters can be set in the identification parameters. In the GUI they are under _Import Filters_ in the _Advanced Settings_. In CLI, you can set them using the arguments at the link below.
https://github.com/compomics/compomics-utilities/wiki/IdentificationParametersCLI#import-filters

The fact that PeptideShaker does not recognize the modifications from the search engine output is generally due to a mismatch between the identification parameters used for the search and the ones used to interpret the results. This can come from different sources:
1- If you have custom modifications, these saved upon starting the search and passed to PeptideShaker via the identification parameters. If you used the zip option, the identification parameters will be packaged along with the search engine results and used by PeptideShaker.
2- When running the search engines, it can be that SearchGUI needs to add modifications to your parameters, e.g. for X!Tandem quick acetyl or quick py(r)rolidone. The parameters after the search therefore contain new variable modifications.
3- When using modifications that are not supported by search engines (e.g. protein terminal modifications with X!Tandem or modifications at amino acid motifs) SearchGUI uses the closest related modification (e.g. peptide terminal modifications or modifications at single amino acids) and PeptideShaker subsequently filters out the peptides that do not match your search. In this case it is normal that many peptides get filtered out.

It could also be that the modifications from the search engine result file cannot be mapped back to the ones used during the search. This is unlikely to happen if you used SearchGUI, though.

Hope this helps,

Marc

**Comment by mvaudel** [comment]
Sorry that I was not clear enough! After clicking _New Project_ and selecting your SearchGUI file, click _Edit_ in front of _Identification_ in the _Project Settings_ panel. In the _Identification Settings_ dialog, click _Show Advanced Settings_, _Import Filters_ is the fourth advanced setting menu from the top :)

**Comment by wolski** [comment]
Hi.

Sorry still lost.  You are speaking about his dialog?

![pepshakenewproj](https://cloud.githubusercontent.com/assets/1926513/23558470/06c1daa4-0034-11e7-8e8a-0a176be5a1da.jpg)

Also I find worrying that 99.9% of my peptides have length less than 8 or greater than 30?
Fri Mar 03 16:59:50 CET 2017        24847 of the best scoring peptides were excluded by the import filters:
Fri Mar 03 16:59:50 CET 2017            - 99.9% peptide length less than 8 or greater than 30.

**Comment by mvaudel** [comment]
Hi again,

Yes, if you click on _Edit_ on the _Identification_ line of the _Project Settings_ panel, you will be able to edit the parameters.

The percentage refers to the reason why peptides were excluded, ie it is 99.9% of the 24,847 peptides and not 99.9% of all peptides. I don't know how many spectra you have in your dataset but with 11 raw files that can be a lot :)

Hope this helps,

Marc

**Comment by wolski** [comment]
Thank you.
