### ISSUE TITLE
Search w same mgf and parameters gives different # of IDs in PeptideShaker if using tandem alone or multiple engines

### ISSUE THREAD

**Issue by akwalker** [compomics/peptide-shaker#253]
I like to search with tandem alone in SearchGUI for speed initially, then if I think the parameters are OK, I add the other search engines (MGGF+, Comet, OMSSA, etc.). 

Using tandem alone, PS is reporting that it identified 11.1% of the spectra searched. I have the same search (mgf and params file) but with several engines and the spectrum ID tab shows that tandem has identified 15.9% of the spectra. Overall the IDs are up to 22.2% so I am looking at tandem only for that number. I didn't change anything other than adding search engines so I am not sure how tandem has identified an additional 3500 spectra.

**Comment by mvaudel** [comment]
Hi,

When aggregating the results of multiple search engines, we take into account search engine agreement to select the best hit of every spectrum. If another search engine correctly identifies a spectrum where X!Tandem had a false identification, the correct match will be retained. In the plots of the Spectrum ID tab you get an idea of the contribution of every search engine to the final results but not the results as processed by the search engine alone. We display these more for quality control, so that you can check whether something went wrong with a given search engine, but they need to be interpreted in the context of the project.

Hope this clarifies this result,

Marc
