### ISSUE TITLE
problems importing FASTA database: non unique accession number

### ISSUE THREAD

**Issue by bpalanski** [compomics/peptide-shaker#285]
I'm trying to import a FASTA database with decoys already appended with the prefix XXX_. I can't use PeptideShaker to generate my decoy database directly, because for my dataset, it is important to use a shuffled rather than a reversed sequence.

When I try to load my FASTA file, I get the message "non unique accession number: XXX_sp". Any ideas how to fix this?

**Comment by hbarsnes** [comment]
If you get the warning "non unique accession number: XXX_sp" this means that you have non-unique accession numbers in your custom FASTA file the way it is currently set up. This is most likely related to the way the you've added the decoy tags. In general, you need to add the decoy tags in such a way that they do not mess up the parsing of the FASTA header, which is required to be able to pick up which part of the header that it the accession number, and which thus have to be unique.

By adding the prefix the way to currently do you change the format of the header, resulting in that we can no longer parse it as a SwissProt/UniProt header. You need to add the decoy tag to the accession number itself.

For example:
>sp|Q9NSD7|RL3R1_HUMAN ...
should become
>sp|Q9NSD7_REVERSED|RL3R1_HUMAN ...

Note also that we only support suffix tags and the tag has to be "_REVERSED". The search will work fine also for custom tags, but PeptideShaker will be unable to calculate the FDR as it cannot pick up the decoys.

But if you change the decoy tags from prefix to suffix, i.e. "XXX_" to "_REVERSED", and add them to the accession number instead of to the start of the header, you should be able to load the data in PeptideShaker.

**Comment by hbarsnes** [comment]
Issue assumed resolved. If this is not the case, please let us know and we'll reopen the issue.
