### ISSUE TITLE
Issues with Commandline

### ISSUE THREAD

**Issue by stickenstein** [compomics/peptide-shaker#304]
Greetings,

We have an issue when using any version later than 1.16.15.

We receive the following error:

```
Thu Apr 12 14:30:44 EDT 2018 Unzipping searchgui_out.zip.

10% 20% 30% 40% 50% 60% 70% 80% 90% 100%

Thu Apr 12 14:30:59 EDT 2018 An error occurred while creating the PeptideShaker project.

java.lang.NullPointerException

	at com.compomics.cli.identification_parameters.IdentificationParametersInputBean.updateIdentificationParameters(IdentificationParametersInputBean.java:2242)

	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.createProject(PeptideShakerCLI.java:650)

	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.call(PeptideShakerCLI.java:218)

	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.main(PeptideShakerCLI.java:938)
```

The command being run is (partial python snippet):

```
"eu.isas.peptideshaker.cmd.PeptideShakerCLI", \
 "-out", "output.cpsx" \
 "-experiment", projectfull, \
 "-sample", protein, \
 "-replicate", "00", \
 "-identification_files", "searchgui_out.zip"
```
searchgui_out.zip was generated by SearchGUI 3.2.20 and the exact same command (with the same files) works on PeptideShaker 1.6.15

Is there some compatibility issue with different versions, eg format of the parameter file changed? We haven't been able to update to SearchGUI 3.2.22 due to what appears to be an issue with XTandem parameter file (haven't finished diagnosing the issue yet).

Thanks!

**Comment by hbarsnes** [comment]
Hi,

The problem seems to be related to the parsing of the search parameters, but I don't really see what the problem is. Would it be possible for you to share the data so that we can try to reproduce the error?

It might also be an option to recreate the parameter file in the latest release and provide this one as input via the -id_params option?

> Is there some compatibility issue with different versions, eg format of the parameter file changed?

Not intentionally, but we are in the process of a major refactoring so it could be that some changes were included that should not have been. All of the search engines work fine in my tests though. So I'd be very keen on knowing about cases were it fails. 

Best regards,
Harald

**Comment by stickenstein** [comment]
Thank you for the quick reply and for all your work as these are wonderful programs.

I did more investigating and it appears as though the issue is when "Digestion" in the Spectrum Matching settings (in SearchGUI) is set to "Unspecific". When I changed "Digestion" to "Enzyme" and set an enzyme, etc., the issue goes away. 

I verified this by changing the setting back and forth a few times.

I don't know if this is intended behavior.

**Comment by hbarsnes** [comment]
Ah, I see what the problem is now. It's due to a minor change that was not tested properly where we tried to extract the enzyme specificity from the enzyme setting, but if no enzyme is set this of course breaks down. I'll make a fix and release new versions later today.

**Comment by hbarsnes** [comment]
I've just released new versions of both SearchGUI and PeptideShaker that should solve the issue with the unspecific enzymes. If this is not the case, please let me know and I'll reopen the issue.

As for the X! Tandem issues you were referring to it would be great if you could open a separate issue if the problem is still occurring?
