### ISSUE TITLE
PSM shows PTM (+58) location to be on H - but Spectrum ID results show the PTM on C or K

### ISSUE THREAD

**Issue by 1Moe** [compomics/peptide-shaker#306]
Hi Marc and Harald,

I am looking for a PTM +58 which could be on either of H, C, or K. 
In the given peptide (screenshots) the PTM location is assigned on either C or H under the PSM tab.
But when I click on the PSM (H+58), the spectrum Identification Results show that the PTM is sitting either on K or on C. This seems slightly strange because it's not on the H as indicated in the PSM. 
From the b10 ion mass (1058 m/z) it seems to me that the +58 PTM can't actually be sitting on the H but has to be on either C or K.

I've attached 3 screenshots to explain it a bit more, perhaps you could help me understand this behaviour in peptide shaker.

I'm leaning towards assigning the PTM to C rather than to H or K because: 
i) the b10 ion at 1058m/z precludes H+58 because the b10(H+58) would be at 1116 m/z.
ii) b12 is at 1333m/z in the X-tandem spectrum, which indicates it can't be at the K (b12 would have to be 1275m/z) - unfortunately the b12 ion is not visible in the Comet spectrum
iii) if K was +58 it may not have been hydrolysed by trypsin at that K (not a very strong argument perhaps)

What do you think?
![psm_question1](https://user-images.githubusercontent.com/12740165/39554371-84f7db4e-4ec6-11e8-820b-3c6dfeb5818a.PNG)
![psm_question2](https://user-images.githubusercontent.com/12740165/39554372-852d8640-4ec6-11e8-8f28-d5fbf1d9c84c.PNG)
![psm_question3](https://user-images.githubusercontent.com/12740165/39554373-855d5744-4ec6-11e8-858a-de8ecc43eec1.PNG)

**Comment by hbarsnes** [comment]
Hi Moe,

Note that the color coding of the PTM (the dark font on the white background, instead of white font on dark background) indicates that PeptideShaker is unsure where the PTM is located. However it has to be put somewhere on the peptide sequence, and it should pick the most likely location based on the PTM scores. But sometimes there is simply not enough evidence from the PSMs to make a clear decision, which, for example, seems to be the case for the result from X! Tandem due to the low number of annotated peaks.

To get a better view on why the PTM is placed where it is, I'd recommend taking a look at the Modifications panel in PeptideShaker for the given PSMs. It shows you the individual PTM scores and hopefully provides more information on why the PTM was located where it was.

You can also find more information about how the PTM scoring works in our tutorial: https://compomics.com/bioinformatics-for-proteomics/identification. See chapter 1.6 on PTM Analysis.

Best regards,
Harald

**Comment by 1Moe** [comment]
Thanks Harald, that helps!
