### ISSUE TITLE
PeptideShaker 1.16.27 error

### ISSUE THREAD

**Issue by IgorFesenko** [compomics/peptide-shaker#328]
Hi team,

I have a problem with opening my search results by PeptideShaker. Could you please help meto resolve this problem?

Best,
Igor

[bug report.txt](https://github.com/compomics/peptide-shaker/files/2385608/bug.report.txt)

**Comment by hbarsnes** [comment]
Hi Igor,

I'm afraid this is a known issue. The good news is that it should be fixed in the new major release of PeptideShaker. But there will still be some time until the new version is ready. In the meantime the only known "fix" is to increase the memory given to PeptideShaker. This at least reduces the chance of the error occurring. You can do this via the Welcome Dialog > Settings & Help > Settings > Java Settings.

Best regards,
Harald

**Comment by hbarsnes** [comment]
This issue should hopefully be solved in the new beta releases of SearchGUI and PeptideShaker. Please see https://groups.google.com/forum/#!topic/peptide-shaker/1ecY0IyMOBM for more details.

If the issue still exists in the beta releases, please open a new issue at https://github.com/compomics/peptide-shaker-2.0-issue-tracker/issues.

If the issue has been solved, it would also be great of you could let us know by replying to this original issue and letting us know. :)

**Comment by hbarsnes** [comment]
This issue should hopefully be fixed in the new release that is available now. If not, please let us know by opening a new issue.
