### ISSUE TITLE
Error when importing data into PeptideShaker

### ISSUE THREAD

**Issue by StephanievL** [compomics/peptide-shaker#333]
Hi, 

I just tried to open the data out of SearchGui and once it was almost finished an error occurred which cancelled the import of my data. 
Here is a print screen of the error. 
Could you please help me out? 
Thanks!

![error peptide shaker](https://user-images.githubusercontent.com/43640704/46142672-9e5e8680-c24f-11e8-9166-1a2936a5b3f2.png)

Stephanie

**Comment by hbarsnes** [comment]
Hi Stephanie,

Could you share the PeptideShaker log file? You'll find it via the Welcome dialog > Settings & Help > Help > Bug Report. This should make it easier to locate the source of the problem.

Best regards,
Harald

**Comment by StephanievL** [comment]
Hi Harald,

Thanks for your fast response!
Here is the Bug Report. Hopefully you can help me out. 

Kind regards, 
Stephanie
[PeptideShaker 1.16.29 log.txt](https://github.com/compomics/peptide-shaker/files/2423987/PeptideShaker.1.16.29.log.txt)

**Comment by hbarsnes** [comment]
Hi Stephanie,

Thanks for the log file. Sadly this seems to be yet another error related to the PeptideShaker backend and the way the memory is handled. This will be fixed in the next major PeptideShaker release, but it will still take some time before this one becomes available. In the meantime the only known fix is 
to increase the memory provided to the tool. This is done via the Welcome dialog > Settings & Help > Settings > Java Settings. Would this be an option for you?

Best regards,
Harald

**Comment by StephanievL** [comment]
Hi Harald, 

Thanks for your suggestion! 
It did work and have my data imported into PeptideShaker :). 

Kind regards, 
Stephanie
