### ISSUE TITLE
Best way to run multiple instances of PeptideShaker

### ISSUE THREAD

**Issue by chrishuges** [compomics/peptide-shaker#345]
Hi,

I have a general question about running PeptideShakerCLI. What is the best way to run multiple instances (if possible) of PeptideShakerCLI without having them interfere with one another? I am running from the command line and all machines are remotely accessed and are processing files hosted on a shared network resource. The PeptideShakerCLI files are also stored and accessed on the shared resource.  

1. Having a single PeptideShakerCLI.jar file. Running PeptideShakerCLI on different machines but all machines are pointing to the same PeptideShakerCLI file?

2. Having multiple PeptideShakerCLI files and each different machine points to its own PeptideShakerCLI file?

Hopefully that makes sense.

Thanks,
Chris

**Comment by hbarsnes** [comment]
Hi Chris,

I'm afraid that with the current release it is not recommended to run more than one instance of the same jar file at the same time. This is due to the backend which would cause the individual PeptideShaker instances to use the same database. You will therefore have to duplicate the PeptideShaker jar file (and the supporting files and folders) to each node. Then each command line is independent and they should not interact with each other.

This issue is partly why we're spent a long time redesigning the backend such that cases like this should be better supported. The new version is still in development, but we have now finally come to the stage of fixing issues and have hopefully left the bigger changes behind.

Best regards,
Harald

**Comment by hbarsnes** [comment]
This issue should hopefully be fixed in the new release that is available now. If not, please let us know by opening a new issue.
