### ISSUE TITLE
Duplicate key in peptide shaker

### ISSUE THREAD

**Issue by chrishuges** [compomics/peptide-shaker#353]
I know this error has been posted a few times before, and I have gone through those old threads. I thought I might add a different perspective for it here though, so I made a new post. 

Basically I see this same peptide key error that has been noticed before. 

```
Attempting to create duplicate peptide key: ICCCPRCCSSECCSPR_6.0201290268000065 from peptide ICCCPRCCSSECCSPR_10.008268600400015-ATAA-6_6.0201290268000065.
```

In this case, I am searching these data as a triple SILAC setup (lysine +4, +8, arginine +6, +10). This is just a single 60-minute run, Orbitrap MS2, nothing otherwise special, not a large file. I am searching with X!Tandem, MS-GF+, and Tide. I am using PeptideShakerCLI, version 1.16.38. That is the error I get above. 

I know before it is stated that this is a memory issue or with how PeptideShaker handles memory. In this instance, I have given PeptideShaker 400g of RAM. I also tested giving it up to 1200g of RAM, and it makes no difference. If I just search this file as a double SILAC experiment, I have no issue (likely as I am not identifying that peptide). If I search this file as triple SILAC, but without MS-GF+, I also have no error. So, in the meantime, I can use other search engines and just avoid MS-GF+, but it would be nice to not have to. The peptide key itself looks odd to me.

Not sure if any of this info is useful.

Thanks!
Chris

**Comment by hbarsnes** [comment]
Hi Chris,

> I know before it is stated that this is a memory issue or with how PeptideShaker handles memory.

Well, yes and no. It is a combination of memory handling (linked to how the data is written to the PeptideShaker database) and the use of multithreading. The combination simply sometimes results in the PeptideShaker backend getting out of sync.

This is often connected to the mapping of PTMs, which generally gets more complicated the more search engines you use.  Which most likely explains why excluding MS-GF+ solves (or rather gets around) the issue in your example above.

Properly solving all of this required that we more or less rewrote the entire PeptideShaker backend, which is why it has been taking so long to fix this particular issue. But we are getting close and we hope that a new PeptideShaker version will be available for testing within not too long.

Best regards,
Harald

**Comment by hbarsnes** [comment]
This issue should hopefully be solved in the new beta releases of SearchGUI and PeptideShaker. Please see https://groups.google.com/forum/#!topic/peptide-shaker/1ecY0IyMOBM for more details.

If the issue still exists in the beta releases, please open a new issue at https://github.com/compomics/peptide-shaker-2.0-issue-tracker/issues.

If the issue has been solved, it would also be great of you could let us know by replying to this original issue and letting us know. :)

**Comment by hbarsnes** [comment]
This issue should hopefully be fixed in the new release that is available now. If not, please let us know by opening a new issue.
