### ISSUE TITLE
Error While Saving project after changing fdr threshold 

### ISSUE THREAD

**Issue by MohmedSoudy** [compomics/peptide-shaker#355]
![Untitled](https://user-images.githubusercontent.com/28669247/56661484-1edc4d00-66a2-11e9-92a2-3105b72fceaa.png)

**Comment by hbarsnes** [comment]
Hi Mohmed,

I'm afraid this error is due to an error in the PeptideShaker backend related to how we handle the memory. The good news is that we are in the process of finishing a new release of PeptideShaker that should solve these issues. The bad new is that we cannot at this time tell you when this new version will become available. But I'll be sure to let you know as soon as it is ready for testing.

Best regards,
Harald

**Comment by hbarsnes** [comment]
This issue should hopefully be solved in the new beta releases of SearchGUI and PeptideShaker. Please see https://groups.google.com/forum/#!topic/peptide-shaker/1ecY0IyMOBM for more details.

If the issue still exists in the beta releases, please open a new issue at https://github.com/compomics/peptide-shaker-2.0-issue-tracker/issues.

If the issue has been solved, it would also be great of you could let us know by replying to this original issue and letting us know. :)

**Comment by hbarsnes** [comment]
This issue should hopefully be fixed in the new release that is available now. If not, please let us know by opening a new issue.
