### ISSUE TITLE
Transcriptome validation

### ISSUE THREAD

**Issue by jordur** [compomics/peptide-shaker#363]
Hi all!
I have done a SearchGUI search of one .mgf file using a transcriptome database which results seem to be really good. However, I have a couple of questions regarding their validation:
1. As you can see in the images below, results using a Fragment m/z Tolerance on SearchGUI of 0.5 or 0.6 Da differ, not in the first hit (which give rise to similar proteins and peptides), but in the remaining identifications. What actually I think is that some of them are included as a "related proteins", but how can I get the entire list of matching proteins and peptides? Should I use the export Extended Report option?
RESULTS 0.5 Da
![results_0 5](https://user-images.githubusercontent.com/3415289/60590452-46375080-9d9c-11e9-9069-28efb5a8f717.png)
RESULTS 0.6 Da
![results_0 6](https://user-images.githubusercontent.com/3415289/60591316-80a1ed00-9d9e-11e9-8604-887e144f4958.png)

I mean, Hit 3 (contig33514) which is a identified as a protein with 0.5 Da of tolerance appears to be a related protein with 0.6 Da of tolerance: 
![related](https://user-images.githubusercontent.com/3415289/60591455-c8c10f80-9d9e-11e9-89b9-8c3fd48ce3cc.png)

2. After reading the 1.5 Peptide and Protein Validation tutorial I am not still sure why the second protein of the image below was considered not validated.
![0 5_notvalid](https://user-images.githubusercontent.com/3415289/60590445-420b3300-9d9c-11e9-9e4c-d2a730ce209a.png)

I mean, given a certain confidence of the finding of a protein identified in our transcriptome database, how can we consider that the protein is not a FP? How a lab technician that receives those results could decipher whether it is a real protein given the fact (image below, Hit 3) that proteins with 0% confidence were well identified.
![well](https://user-images.githubusercontent.com/3415289/60591813-86e49900-9d9f-11e9-9f40-7a144c1815cc.png)

Thank you very much for your help and congratulations for your great job!

**Comment by hbarsnes** [comment]
Hi,

> How can I get the entire list of matching proteins and peptides? Should I use the export Extended Report option?

Yes, that is one option, but clicking the protein inference (PI) column the way you have done is perhaps easier when you're inspecting a particular protein group.

> After reading the 1.5 Peptide and Protein Validation tutorial I am not still sure why the second protein of the image below was considered not validated.

The short answer is that you simply do not detect enough proteins for the statistical validation to be meaningful. In such cases you mainly have to rely on a manual inspection of the results in in order to decide what to trust.

Best regards,
Harald

**Comment by jordur** [comment]
Ok. So in your opinion, a manual inspection of obtained peptides should be mandatory, right? 
I just explained to my workmates some advantages about SearchGUI + PeptideShaker over our own transcriptome database but they just argued that it will be still a slow process and that they cannot rely on results. Further, I will try to find out a filter in order to reduce the number of peptides by pkl file not just the confidence.
Any help in this sense will  be appreciated.
Kind regards,

**Comment by hbarsnes** [comment]
Hi again,

Yes, the manual inspection for this kind of data should be mandatory given that the statistical validation cannot really be trusted. But it is important to highlight that this is independent of the software used. Just because Mascot does not tell you about the issues with the statistical validation it does not mean that the issues are not there. Hence sticking with Mascot may not really solve the issue, but rather ignore that is exists in the first place.

One thing I just noted though is that it seems like you are using an FDR threshold of 0.05 in Mascot, while the standard threshold in PeptideShaker is 0.01. Perhaps being less strict also in PeptideShaker will provide more similar results? You can change the threshold in PeptideShaker via the Advanced settings in the Identification Settings dialog and the Validation Levels option. This has to be done before loading the data.

Best regards,
Harald
