### ISSUE TITLE
Custom Report 

### ISSUE THREAD

**Issue by jordur** [compomics/peptide-shaker#370]
Hi all! 
I am trying to get a custom report from the attached PeptideShaker project using the GUI. To do that, I tried to add a new report type in order to obtain certain information such as the Main Accession from Protein Identification Summary or the Algorithm Score from the Identification Algortithm Results. However I got a file just with the header line (Figure 1) 
![Figure1](https://user-images.githubusercontent.com/3415289/61946553-34178f00-afa3-11e9-8d7f-bd02d09ee254.png)
What I am doing wrong? How should proceed in order to obtain the custom report?
Thank you in advance
Attached project
[CTO_5a.zip](https://github.com/compomics/peptide-shaker/files/3435406/CTO_5a.zip)

**Comment by hbarsnes** [comment]
Hi,

My guess would be that you do not have any validated matches, as by default only the validated matches are included in the reports. You can change this by unselecting the "Validated Only" option under the "Matches" category in the Settings section when creating your custom report.

If this does not help, please share the PeptideShaker project via Export > PeptideShaker Project As > Zip File, as otherwise the project cannot be opened. And please also provide access the custom report by sharing the file "user home"\.peptideshaker\exportFactory.cus.

Best regards,
Harald

**Comment by jordur** [comment]
Exactly! That was the reason. Thank you very much for your help and time!
