### ISSUE TITLE
Novor results

### ISSUE THREAD

**Issue by KunathBJ** [compomics/peptide-shaker#384]
Hello,

I ran the latest version of SearchGui successfully with couple of search engine as well as with novor.
However, I am not entirely sure I understand how searchGui/Peptide shaker uses the information from novor.

My questions then are: 
What happen to the peptide predicted by novor? Are they used against the database I provide? If yes, then what the interest of running novor?
Secondly, is it possible to extract the peptide (or associated spectra) that were produced by novor? For further search of initially unidentified spectra for example.

Thanks a lot for your help!!

Ben

**Comment by hbarsnes** [comment]
Hi Ben,

When running Novor as part of the SearchGUI/PeptideShaker pipeline it is basically used as just another search engine and the identified peptides are mapped to the provided sequence database.

If you want to inspect the Novor output independently of a sequence database, we recommend taking a look at [DeNovoGUI](http://compomics.github.io/projects/denovogui.html) or simply opening the Novor output directly.

Note that due to Novor always returning complete peptide sequences the results will probably not be very different from a "normal" search engine when mapped to a sequence database.

You may see a bigger difference in the results when comparing DirecTag to the "normal" search engines, as DirecTag returns shorter tags instead of complete peptide sequences. But we have not carried out these sorts of comparisons in detail.

Best regards,
Harald

**Comment by KunathBJ** [comment]
Hi Harald,

So the .novor file I get in the zip searchgui_out can be directly feed into  DeNovoGUI?
Or is it another file that I should use?

Thanks a lot for the help/fast answer!
Ben

**Comment by hbarsnes** [comment]
Hi Ben,

You should be able to load the .novor files from SearchGUI into DeNovoGUI, but it is probably easier to simply run Novor directly via DeNovoGUI to avoid any issues in the transfer between the two tools.

Best regards,
Harald

**Comment by KunathBJ** [comment]
Perfect. Will do then!

Thanks a lot again for your help.
