### ISSUE TITLE
Use local FDR instead of global

### ISSUE THREAD

**Issue by iquasere** [compomics/peptide-shaker#434]
Greetings!

Is it possible to select protein identifications by local FDR, instead of global, in Peptide-Shaker?

**Comment by mvaudel** [comment]
Hi,
The value reported in the "confidence" column is equivalent to `1 - local FDR`, a confidence of 95% would mean a local FDR of 5%. You can change the threshold to use confidence instead of FDR either when creating your project (using the "Validation Parameters" in the advanced parameters) or once the project is created (in the "Validation" tab). Selecting a confidence threshold of 95% will retain all matches before the first match with a confidence under 95% for matches ordered in decreasing score.
Hope it helps,
Marc

**Comment by iquasere** [comment]
Thank you, Marc and Harald. Keep up the good work ^^
