### ISSUE TITLE
Reports: Algorithm score

### ISSUE THREAD

**Issue by tivdnbos** [compomics/peptide-shaker#439]
When I made a new report type with algorithm score, I get on each line the following "X!Tandem (0.0)", while the Algorithm confidence is different.
I think a rounding error occurred here. I think, whenever a user explicitly asks for this, I would give the full float without rounding.

**Comment by hbarsnes** [comment]
Thanks for the tip! It actually turned out not to be a rounding error, but rather that the raw scores were not stored for X! Tandem (and several of the other search engines), or rather stored in a different variable. Mainly due to us not having to transform the scores unlike for some of the other search engines. This worked fine internally (as we do not really use the raw scores), but for this particular export the raw scores are used.

This has now been corrected. Additionally, the algorithm score will now exists as two separate export features: Algorithm Raw Score and Algorithm Score, where the former represents the unchanged score given by the search engine, while latter represents the potentially transformed score that is used in the further processing in PeptideShaker. (For some search engines, such as X! Tandem, the values will be identical.)

It all seems to work as wanted, but I'll do some more testing tomorrow and then hopefully release a new PeptideShaker version. Note that you will have to reprocess the data in PeptideShaker for the new fix to take effect.

**Comment by hbarsnes** [comment]
I've just released PeptideShaker 2.0.12 which should solve this problem. If this is not the case, please let me know and I'll reopen the issue.
