### ISSUE TITLE
PeptideShakerCLI version 2.0.16

### ISSUE THREAD

**Issue by CarlaCristinaUranga** [compomics/peptide-shaker#449]
Hi, is there a way of fixing this error?

[PeptideShaker.log](https://github.com/compomics/peptide-shaker/files/6213500/PeptideShaker.log)

Thank you!

Carla Uranga

**Comment by hbarsnes** [comment]
Seems to be an issue with the database temp folder not being set on your system. Maybe you can try something like this: https://github.com/xerial/sqlite-jdbc/issues/97#issuecomment-429252592

The second solution (i.e. adding `-Djava.io.tmpdir=/var/run/some-other-location` to your PeptideShakerCLI command line) looks like the easiest option?

**Comment by CarlaCristinaUranga** [comment]
*Here are my command line arguments: I am afraid I am not sure this is
right, I am not familiar with SQL. Would you mind correcting my CLI
arguments? Thank you!*


*nohup java -Xmx20G -cp PeptideShaker-2.0.16.jar
eu.isas.peptideshaker.cmd.PeptideShakerCLI;
**-Djava.io.tmpdir=**/local/ifs2_projdata/0759/projects/DIABETES/curanga/covid_proteomics/temp
-reference saliva -fasta_file
/local/ifs2_projdata/0759/projects/DIABETES/curanga/covid_proteomics/databases/rev_human.fasta
-identification_files
/local/ifs2_projdata/0759/projects/DIABETES/curanga/covid_proteomics/results/1DLC12292020QE_Saliva_proteomics_#10.msgf.mzid
-spectrum_files
/local/ifs2_projdata/0759/projects/DIABETES/curanga/covid_proteomics/Saliva/Proteomics/1DLC12292020QE_Saliva_proteomics_#10.mzML
-id_params
/local/ifs2_projdata/0759/projects/DIABETES/curanga/covid_proteomics/SearchGUI-4.0.22/saliva_10ppm_6-50.par
-out
/local/ifs2_projdata/0759/projects/DIABETES/curanga/covid_proteomics/pepshake_results
>sal10_30MB_database.log &*

**Comment by hbarsnes** [comment]
You have to move the -Djava.io.tmpdir option in front of the -cp option, i.e. just before or after the -Xmx20G option. The reason is that it is a general Java option and not an option for PeptideShaker.

**Comment by CarlaCristinaUranga** [comment]
Ok I think it is a memory issue! I was trying to Peptide Shake 50 files at once. So I reduced it to 5. Hopefully it will work now. Thanks Harald!

**Comment by CarlaCristinaUranga** [comment]
Ok peptide shaker is working with 5 files at a time, which is doable, but how can we program report CLI to keep each file separate as a separate sample? Is there a way of turning a .psdb file containing 5 identification files into 5 separate reports? I like to keep the reports separate because we have metadata attached to each. Thank you kindly! 

Carla

**Comment by CarlaCristinaUranga** [comment]
[hs_err_pid150119.log](https://github.com/compomics/peptide-shaker/files/6233724/hs_err_pid150119.log)

I get this error from the report CLI. Anything to worry about?

Best wishes,

Carla

**Comment by hbarsnes** [comment]
> Is there a way of turning a .psdb file containing 5 identification files into 5 separate reports?

Nope. PeptideShaker merges the individual results into one project. If you want separate reports you have to load the data from each sample separately.

 > I get this error from the report CLI. Anything to worry about?

This indicates an internal Java error which is usually memory-related. These are most often not very consistent. I recommend running it once more to see if the problem is reproducible. There is also the known (and yet unsolved) database backend issue in the log. That one is currently only avoided by increasing the memory provided.

**Comment by CarlaCristinaUranga** [comment]
Ok thank you. If you know of any tools that can automate peptide shaker I would greatly appreciate it.

Best wishes,
Carla

**Comment by CarlosHorro** [comment]
Hi @CarlaCristinaUranga ,

PeptideShaker is currently available in a variety of packaging systems in order to facilitate its automatic execution and integration with other tool, highlighting:

- As a Docker container:
https://quay.io/repository/biocontainers/peptide-shaker?tag=latest&tab=tags

- As a Conda package:
https://anaconda.org/bioconda/peptide-shaker

- As a Galaxy tool:
https://toolshed.g2.bx.psu.edu/repository?repository_id=13a5bad5c984db6f


Depending on your use case you may be interested on one of them more than the others.

Greetings,
Carlos

**Comment by CarlaCristinaUranga** [comment]
Hi Carlos,

I definitely prefer the Conda package and have installed it. However, how do the commands work with this package? I am having trouble with this. Also, do you use snakemake or some kind of script language to automate file processing keeping input and output files separate? I totally appreciate any help you may have with this.
Best wishes,
Carla

**Comment by CarlosHorro** [comment]
Hi @CarlaCristinaUranga ,

Once you have the Conda package installed and activated, executing PeptideShakerCLI is done almost in the same way than usually. Just instead of calling to PeptideShakerCLI class into the PeptideShaker jar package (as in `java -cp PeptideShaker-version.jar eu.isas.peptideshaker.cmd.PeptideShakerCLI`), you call to the class via _peptide-shaker_ script (_peptide-shaker eu.isas.peptideshaker.cmd.PeptideShakerCLI_). As a full example:

`peptide-shaker eu.isas.peptideshaker.cmd.PeptideShakerCLI -reference x -fasta_file input_fasta_file.fasta -identification_files sg_output.zip -spectrum_files spectra.mgf -id_params IdentificationParameters.par -out test.psdb
`
instead of

`java -cp PeptideShaker-version.jar eu.isas.peptideshaker.cmd.PeptideShakerCLI -reference x -fasta_file input_fasta_file.fasta -identification_files sg_output.zip -spectrum_files spectra.mgf -id_params IdentificationParameters.par -out test.psdb`

About snakemake, we do not use it or similar alternatives, although, as we also have a Galaxy tool which reuses the Conda package, this Galaxy tool executes many tests providing specific inputs and guaranteeing the stability of the outputs.

Greetings,
Carlos

**Comment by CarlaCristinaUranga** [comment]
Hi Carlos thank you for suggesting galaxy! I downloaded Galaxy and installed PeptideShaker as a tool. It looks promising but of course there will be a learning curve for me :). I am currently uploading data and am getting errors. Is there a specific data format I need to implement? I have .mzML files and msgf.mzid.gz identification files. Here is a screen shot of the errors I am getting:

<img width="1424" alt="Screen Shot 2021-04-12 at 11 27 15 AM" src="https://user-images.githubusercontent.com/22406027/114443106-255f7a00-9b82-11eb-8ed2-96cce0b0992e.png">

Any guidance would be greatly appreciated!

Best wishes,

Carla

**Comment by CarlosHorro** [comment]
Hi @CarlaCristinaUranga ,

Yes, Galaxy is a really interesting platform that tries to make "automatic" the installation and execution of many tools (from a wide variety of sources), and it also makes possible to create (graphically) workflows among them in such a way that the outputs of some tools are connected to the inputs of others, just knowing that both inputs and outputs have the same type.

I am not sure about the reason why Galaxy failed when you tried to upload some mzMLs files, specially when you previously uploaded one...

More importantly, if you want to use PeptideShaker in Galaxy, you firstly need to execute SearchGUI and the output produced by SearchGUI ("searchgui" file type in Galaxy) will be recognised as a valid input in PeptideShaker tool.

The overall workflow to be executed would be:
Identification Parameters -> SearchGUI -> PeptideShaker
(FastaCLI) ->

All those tools are also installed when you downloaded PeptideShaker tool.

SearchGUI requires as input parameters:
- Identification Parameters file (.par) generated by the tool of the same name
- Fasta file with decoys in the format undestood by SearchGUI. 
If you do not have it, you have to execute the FastaCLI tool which accepts a fasta file as input and returns a fasta file (with the proper decoys sequences) as output.
- Peak list file, in mzml or mgf formats.

Once you have those inputs you will be able to choose them in SearchGUI tool, which will produce the output accepted by PeptideShaker.

In order to automatise all this procedure, I recommend to investigate the workflows functionality. It is based on a graphical editor in which you can connect all tools using their inputs/outputs. Once you have defined and saved it, you just have to provide to the workflow the initial inputs and the worflow will execute all the different tools step by step.

**Comment by hbarsnes** [comment]
Issue assume resolved. If this is not the case, please let us know and we'll reopen the issue.
