### ISSUE TITLE
<CompomicsError>PeptideShaker processing failed.

### ISSUE THREAD

**Issue by mndavies286** [compomics/peptide-shaker#451]
Hello

I'm trying to run the latest Docker Image of peptide-shaker 2.0.15

quay.io/biocontainers/peptide-shaker:2.0.15--h779adbc_1

I'm running the command:

peptide-shaker eu.isas.peptideshaker.cmd.PeptideShakerCLI -reference test_cmd_ref -fasta_file target.fasta -identification_files searchgui_out.zip -spectrum_files samples -id_params test.par -out outfolder/test.psdb

The job fails to produce the output file and the command.log gives the following error. Can anyone explain what's causing this error?

nxf-scratch-dir ip-172-31-34-56:/tmp/nxf.XXXX4IK24f
<CompomicsError>PeptideShaker processing failed. Please see the PeptideShaker log file: /usr/local/share/peptide-shaker-2.0.15-1/resources/PeptideShaker.log</CompomicsError>

Many thanks

**Comment by CarlosHorro** [comment]
Hi @mndavies286 ,

Sorry for the delay in my response, we have seen your issue and we will look into it as soon as possible (probably on next days).

Greetings,
Carlos

**Comment by CarlosHorro** [comment]
Hi @mndavies286 ,

I've tried to reproduce your error installing and executing the same PS docker image with equivalent commands in my system (Ubuntu 20.04) but peptideshaker worked for me.
In order to have more information, could you please send me the content of your log file?
You can set a custom log folder using the "-log" parameter, like:


docker run -v <local-folder>:/myresources <docker-image-id> peptide-shaker eu.isas.peptideshaker.cmd.PeptideShakerCLI -reference test_cmd_ref -fasta_file /myresources/target.fasta -identification_files /myresources/sg_output.zip -spectrum_files /myresources/samples -id_params /myresources/test.par  -out /myresources/outfolder/test.psdb -temp_folder /myresources/outfolder -log /myresources/outfolder

Greetings,
Carlos

**Comment by hbarsnes** [comment]
Issue assume resolved. If this is not the case, please let us know and we'll reopen the issue.
