### ISSUE TITLE
PeptideShaker processing canceled

### ISSUE THREAD

**Issue by Ysraa** [compomics/peptide-shaker#478]
Hi,

I am having trouble with certain files not being able to be processed. When I start the search on searchgui it asks to overwrite. Then it gives some errors in the report as you can see in the screenshot attached. I have no idea how to fix this. It works fine with other files.

Best regards!
![image](https://user-images.githubusercontent.com/97061550/147978342-dd3ef962-2b66-43ea-9ec6-b6706e4b5356.jpg)

**Comment by hbarsnes** [comment]
Hi! The problem here (at least the one shown in the screenshot) is that MS-GF+ filters out all of the spectra. You can either switch to a different search engine in SearchGUI or change the MS-GF+ settings. If going for the latter, I would recommend having a look at the Fragmentation Method option in the MS-GF+ advanced settings which you can find by clicking the cog while icon to the right of where you select MS-GF+ in the main SearchGUI dialog. Hopefully changing this setting will result in MS-GF+ not filtering out all of your spectra.
