### ISSUE TITLE
An error occurred: Not enough representative modification sites found.

### ISSUE THREAD

**Issue by danyunghsu** [compomics/peptide-shaker#517]
Hi,
I'm running a searchGUI file processed in msgf in peptideshaker, and i recieve this message "An error occurred: Not enough representative modification sites found". I find a same question #Importing data cancelled. Processing failed. Not enough representative PTM sites found #80# but i'm now using the 2.2.22 version of peptideshaker. How do i resolve this problem?
Thanks, 
Danyung
[5_msgfQ.txt](https://github.com/compomics/peptide-shaker/files/11771263/5_msgfQ.txt)

**Comment by hbarsnes** [comment]
Hi Danyung,

We are working on a fix for this issue and a new version should soon be available for testing. We'll let you know as soon as the new release is available.

Best regards,
Harald

**Comment by danyunghsu** [comment]
Alright, thank you for clarifying me! I'll wait for the new version then :)

**Comment by hbarsnes** [comment]
A beta version that should fix this issue is now available for testing here: https://genesis.ugent.be/maven2/eu/isas/peptideshaker/PeptideShaker/3.0.0-beta/PeptideShaker-3.0.0-beta.zip

Note that you will have to reprocess the data in PeptideShaker, i.e. you cannot open old PeptideShaker projects directly.

Please let us know if this new version solves the modification issues you were experiencing?

**Comment by danyunghsu** [comment]
Hi Harald,
I tested the same data using this new version, problem fixed. Thank you for your prompt solution.
Danyung
