### ISSUE TITLE
PeptideShaker & Quantification data

### ISSUE THREAD

**Issue by Hartecky** [compomics/peptide-shaker#541]
Hello CompOmics team,

I am working on different proteomics datasets including both label-free and TMT experiments and I have several questions. After performing identification using SearchGUI with X!Tandem algorithm, I wanted to see and validate the results using PeptideShaker, after that I exported the data into .mzid format for further quantitiative & statistic data analysis.

However I noticed that there is a "Fraction" tab in the peptideshaker where I can investigate protein intensities as well as "Quant" column in Proteins Table. Moreover I saw that I can export fractions data as table. My questions:

- Can I use such data for further processing by e.g. QFeatures R package?
- Is this idea appropiate for both label-free and TMT approaches
- Can you recommend any other tool that will work with .mzid file exported by PeptideShaker suitable for quantitative proteomics? (I am linux based, so MaxQuant is not suitable for me)

Thank you very much in advance for a response
Bartlomiej

**Comment by hbarsnes** [comment]
Hi Bartlomiej,

I'm afraid that PeptideShaker does not really support protein quantification, only identification.

For TMT we do have a beta tool called [Reporter](https://github.com/compomics/reporter) that can be used on top of the PeptideShaker output but as it is in a beta state (and its future development uncertain) you are probably better off using other tools instead.

The Fractions tab should not be used for quantitative analysis. It is only meant as a general indication of which peptides and proteins that are found in which fraction when using fractionation. It therefore does not contain data for use in statistical analysis.

The exported PeptideShaker mzid file only contains the identification data, i.e. there is no quantitative information in there, and thus cannot be used for follow-up quantitative analysis.

With regards to other tools, MaxQuant is now also supported on Linux, so that may still be an option. You can also try [MSFragger](https://msfragger.nesvilab.org) or [Skyline](https://skyline.ms/project/home/software/Skyline/begin.view). Using [Sage](https://github.com/lazear/sage) directly, and not via SearchGUI, may also be an option worth considering. (On a related note, the mentioned Quant-column in PeptideShaker comes from the Sage output.)

Best regards,
Harald

**Comment by Hartecky** [comment]
Hi, 

Thank you for your very quick answer. Is there any other way to obtain quantitative data from PeptideShaker like PSMs etc. which will be suitable by other tools for counting? I am asking becaus PeptideShaker seems to be very powerful tool and very intuitive to use so it will be great if quantitative data could be also somehow exported from the tool or avalaible inside it.

Also, I am aware of MaxQuant support on Linux, however I gave it a try, but while doing everything according to the manual still a lot of different errors occur and even when handled, still did not produce the desired results like the file proteinGroups.txt. I guess we need to wait a bit longer for full MaxQuant support on Linux.

Best regards,
Bartlomiej

**Comment by hbarsnes** [comment]
> Is there any other way to obtain quantitative data from PeptideShaker like PSMs etc. which will be suitable by other tools for counting?

No, I'm afraid not. Mainly due to quantification not being our focus when PeptideShaker was initially developed more than 13 years ago. We have always wanted to also support quantification, but sadly do not have the time and resources to implement it.
