### ISSUE TITLE
Not recognizing modifications in example dataset - qexactive01819

### ISSUE THREAD

**Issue by EugKapp** [compomics/peptide-shaker#99]
Hi Guys,

We tried loading the example dataset using version 1.1.3 and are concerned by the following: 94.4% unrecognized modifications. We proceeded as follows: Loaded the example dataset, then exported as mzIdentML. Then re-loaded the mzIdentML and specified the mgf, mzId and fasta file (provided in resources/exampledataset/data).

Mon Nov 30 16:16:23 AEDT 2015            - 94.4% unrecognized modifications.
Should we send or attach the report?

Thanks Eugene and Yunshan

**Comment by hbarsnes** [comment]
Hi Eugene and Yunshan,

Sounds strange that (almost) all of the modifications should be unrecognized. Do you edit the search settings to include the modifications in the original search? (And update the other search settings accordingly?)

In any case, what would be the goal of reloading the exported mzIdentML file back into PeptideShaker?

Best regards,
Harald

**Comment by EugKapp** [comment]
Hi Harald, 

We did not search the data. This is your dataset provided as part of the PeptideShaker download. We were having a few issues loading our own mzId file so my student Yunshan tried using your provided dataset i.e. exporting an mzId and then reloading the same file. There appears to be an issue with how modifications are handled. 

Thanks for your assistance and let me know if you need more information. 

All the best, 

Eugene 

----- Original Message -----

**Comment by hbarsnes** [comment]
Hi Eugene,

When loading search results that are not from SearchGUI you have to provide the search settings in the New Project dialog so that PeptideShaker knows how to parse the data, including the modifications. If this is not done, the modifications will in most cases not be recognized and the data cannot be parsed correctly. (When loading data from SearchGUI the search settings are automatically imported.)

Note also that the percent of unrecognized modifications in itself is not really important, the interesting part is how many of them there are. So in the line above you'll see something like "601 of the best scoring peptides were excluded by the import filters". The percent of unrecognized modifications is thus the percentage of these excluded peptides, and not of all the detected peptides. Hence the percentage could be quite high, but still exclude only a small number of peptides.

How did you create the original mzIdentML file that you had problems loading in PeptideShaker? And what where the issues? If it is from a search engine we haven't yet seen we might need to make some minor changes in our code to load it properly.

Best regards,
Harald

**Comment by EugKapp** [comment]
Thanks Harald. 
  
The example set works fine after following your instructions. 
We currently generate an mzID file using Andy Jones javacsv to convert csv and mgf files to mzID and then load this with appropriate fasta file into PeptideShaker. 
  
I will share a csv file in the coming weeks - and hopefully enable support for my own search algorithm which is cmd line. 
  
I use ProteinProspector for viewing chimeric spectra - any plans for supporting annotation of multiple peptides per spectrum? 
  
All the best, 
Eugene 

----- Original Message -----

**Comment by hbarsnes** [comment]
Hi Eugene,

I guess I should know this, but when you refer to "my own search algorithm" which algorithm are you then referring to? And regarding adding support for it, would it then be interesting to add it to SearchGUI? This would make it much easier to open the results in PeptideShaker.

Regarding viewing chimeric spectra, the limitation is currently not so much in PeptideShaker but more in the algorithms supported as none of these support this as far as I know. I know that MS Amanda is working towards it, but nothing is available yet.

However, we do support the annotation of two sets of sequences on the same spectrum in the Spectrum IDs tab. If you select two PSMs for the same spectrum you'll see the information using mirrored spectra. Selecting more than two uses a bubble plot option. (The same is feature is also supported in most other tabs.) Not sure if this was what you were looking for?

Best regards,
Harald

**Comment by hbarsnes** [comment]
Hi Eugene,

I didn't hear back from you in a long time, so I will now close this issue. The title of the issue does not really fit with the topic anymore either. But please feel free to open a new issue if you have further comments of questions.

Best regards,
Harald
